apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-aspnetcoreapi-deployment
spec:
  selector:
    matchLabels:
      app: hello-aspnetcoreapi-pod
  template:
    metadata:
      labels:
        app: hello-aspnetcoreapi-pod
    spec:
      containers:
      - name: hello-aspnetcoreapi-container
        image: slftest.azurecr.io/hello-aspnercoreapi:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80